#!/usr/bin/env ruby

# Randomly chooses entrants from the database and updates their chosen_
#
# Can be run multiple times as people

$: << "." << File.dirname(__FILE__)

require 'app'

unless ballot_size = ENV["BALLOT_SIZE"]
  abort("BALLOT_SIZE is not defined")
end

ballot_size = ballot_size.to_i
STDERR.puts "Ballot size: #{ballot_size}"

chosen_count = Railscamp::Thirteen::Entrant.chosen.count
STDERR.puts "Chosen count: #{chosen_count}"

remaining_to_choose = ballot_size - chosen_count
STDERR.puts "Remaining: #{remaining_to_choose}"

abort("No more remaining to be chosen") unless remaining_to_choose > 0

entrants = Entrant.unchosen.sample(remaining_to_choose)

STDERR.puts "Updating entrants #{entrants.map(&:id)} as chosen"

chosen_time = Time.now.utc
entrants.each {|e| e.choose!(chosen_time)}

chosen_count = Railscamp::Thirteen::Entrant.chosen.count
STDERR.puts "New chosen count: #{chosen_count}"